using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace mnd.Logic.BC_PandapForms.DataModels
{
    [Table("FORM_YATAYDATA")]
    public class FormYatayData
    {
        [Key]
        public int Id { get; set; }

        public int FormGunlukId { get; set; }
        public Guid SatirGuid { get; set; }
        public string FormAdi { get; set; }

        public DateTime IslemTarih { get; set; }
        public string KullaniciId { get; set; }

        public string CevapJson { get; set; }

        public int? BulunanProblemSayisi { get; set; }

        public string S01 { get; set; }
        public string S02 { get; set; }
        public string S03 { get; set; }
        public string S04 { get; set; }
        public string S05 { get; set; }
        public string S06 { get; set; }
        public string S07 { get; set; }
        public string S08 { get; set; }
        public string S09 { get; set; }
        public string S10 { get; set; }
        public string S11 { get; set; }
        public string S12 { get; set; }
        public string S13 { get; set; }
        public string S14 { get; set; }
        public string S15 { get; set; }
        public string S16 { get; set; }
        public string S17 { get; set; }
        public string S18 { get; set; }
        public string S19 { get; set; }
        public string S20 { get; set; }
        public string S21 { get; set; }
        public string S22 { get; set; }
        public string S23 { get; set; }
        public string S24 { get; set; }
        public string S25 { get; set; }
        public string S26 { get; set; }
        public string S27 { get; set; }
        public string S28 { get; set; }
        public string S29 { get; set; }
        public string S30 { get; set; }
        public string S31 { get; set; }
        public string S32 { get; set; }
        public string S33 { get; set; }
        public string S34 { get; set; }
        public string S35 { get; set; }
        public string S36 { get; set; }
        public string S37 { get; set; }
        public string S38 { get; set; }
        public string S39 { get; set; }
        public string S40 { get; set; }
        public string S41 { get; set; }
        public string S42 { get; set; }
        public string S43 { get; set; }
        public string S44 { get; set; }
        public string S45 { get; set; }
        public string S46 { get; set; }
        public string S47 { get; set; }
        public string S48 { get; set; }
        public string S49 { get; set; }
        public string S50 { get; set; }
        public string S51 { get; set; }
        public string S52 { get; set; }
        public string S53 { get; set; }
        public string S54 { get; set; }
        public string S55 { get; set; }
        public string S56 { get; set; }
        public string S57 { get; set; }
        public string S58 { get; set; }
        public string S59 { get; set; }
        public string S60 { get; set; }
        public string S61 { get; set; }
        public string S62 { get; set; }
        public string S63 { get; set; }
        public string S64 { get; set; }
        public string S65 { get; set; }
        public string S66 { get; set; }
        public string S67 { get; set; }
        public string S68 { get; set; }
        public string S69 { get; set; }
        public string S70 { get; set; }
        public string S71 { get; set; }
        public string S72 { get; set; }
        public string S73 { get; set; }
        public string S74 { get; set; }
        public string S75 { get; set; }
        public string S76 { get; set; }
        public string S77 { get; set; }
        public string S78 { get; set; }
        public string S79 { get; set; }
        public string S80 { get; set; }
        public string S81 { get; set; }
        public string S82 { get; set; }
        public string S83 { get; set; }
        public string S84 { get; set; }
        public string S85 { get; set; }
        public string S86 { get; set; }
        public string S87 { get; set; }
        public string S88 { get; set; }
        public string S89 { get; set; }
        public string S90 { get; set; }
        public string S91 { get; set; }
        public string S92 { get; set; }
        public string S93 { get; set; }
        public string S94 { get; set; }
        public string S95 { get; set; }
        public string S96 { get; set; }
        public string S97 { get; set; }
        public string S98 { get; set; }
        public string S99 { get; set; }
        public string S100 { get; set; }
        public string S101 { get; set; }
        public string S102 { get; set; }
        public string S103 { get; set; }
        public string S104 { get; set; }
        public string S105 { get; set; }
        public string S106 { get; set; }
        public string S107 { get; set; }
        public string S108 { get; set; }
        public string S109 { get; set; }
        public string S110 { get; set; }
        public string S111 { get; set; }
        public string S112 { get; set; }
        public string S113 { get; set; }
        public string S114 { get; set; }
        public string S115 { get; set; }
        public string S116 { get; set; }
        public string S117 { get; set; }
        public string S118 { get; set; }
        public string S119 { get; set; }
        public string S120 { get; set; }
        public string S121 { get; set; }
        public string S122 { get; set; }
        public string S123 { get; set; }
        public string S124 { get; set; }
        public string S125 { get; set; }
        public string S126 { get; set; }
        public string S127 { get; set; }
        public string S128 { get; set; }
        public string S129 { get; set; }
        public string S130 { get; set; }
        public string S131 { get; set; }
        public string S132 { get; set; }
        public string S133 { get; set; }
        public string S134 { get; set; }
        public string S135 { get; set; }
        public string S136 { get; set; }
        public string S137 { get; set; }
        public string S138 { get; set; }
        public string S139 { get; set; }
        public string S140 { get; set; }
        public string S141 { get; set; }
        public string S142 { get; set; }
        public string S143 { get; set; }
        public string S144 { get; set; }
        public string S145 { get; set; }
        public string S146 { get; set; }
        public string S147 { get; set; }
        public string S148 { get; set; }
        public string S149 { get; set; }
        public string S150 { get; set; }
        public string S151 { get; set; }
        public string S152 { get; set; }
        public string S153 { get; set; }
        public string S154 { get; set; }
        public string S155 { get; set; }
        public string S156 { get; set; }
        public string S157 { get; set; }
        public string S158 { get; set; }
        public string S159 { get; set; }
        public string S160 { get; set; }
        public string S161 { get; set; }
        public string S162 { get; set; }
        public string S163 { get; set; }
        public string S164 { get; set; }
        public string S165 { get; set; }
        public string S166 { get; set; }
        public string S167 { get; set; }
        public string S168 { get; set; }
        public string S169 { get; set; }
        public string S170 { get; set; }
        public string S171 { get; set; }
        public string S172 { get; set; }
        public string S173 { get; set; }
        public string S174 { get; set; }
        public string S175 { get; set; }
        public string S176 { get; set; }
        public string S177 { get; set; }
        public string S178 { get; set; }
        public string S179 { get; set; }
        public string S180 { get; set; }
        public string S181 { get; set; }
        public string S182 { get; set; }
        public string S183 { get; set; }
        public string S184 { get; set; }
        public string S185 { get; set; }
        public string S186 { get; set; }
        public string S187 { get; set; }
        public string S188 { get; set; }
        public string S189 { get; set; }
        public string S190 { get; set; }
        public string S191 { get; set; }
        public string S192 { get; set; }
        public string S193 { get; set; }
        public string S194 { get; set; }
        public string S195 { get; set; }
        public string S196 { get; set; }
        public string S197 { get; set; }
        public string S198 { get; set; }
        public string S199 { get; set; }
        public string S200 { get; set; }
        public string S201 { get; set; }
        public string S202 { get; set; }
        public string S203 { get; set; }
        public string S204 { get; set; }
        public string S205 { get; set; }
        public string S206 { get; set; }
        public string S207 { get; set; }
        public string S208 { get; set; }
        public string S209 { get; set; }
        public string S210 { get; set; }
        public string S211 { get; set; }
        public string S212 { get; set; }
        public string S213 { get; set; }
        public string S214 { get; set; }
        public string S215 { get; set; }
        public string S216 { get; set; }
        public string S217 { get; set; }
        public string S218 { get; set; }
        public string S219 { get; set; }
        public string S220 { get; set; }
        public string S221 { get; set; }
        public string S222 { get; set; }
        public string S223 { get; set; }
        public string S224 { get; set; }
        public string S225 { get; set; }
        public string S226 { get; set; }
        public string S227 { get; set; }
        public string S228 { get; set; }
        public string S229 { get; set; }
        public string S230 { get; set; }
        public string S231 { get; set; }
        public string S232 { get; set; }
        public string S233 { get; set; }
        public string S234 { get; set; }
        public string S235 { get; set; }
        public string S236 { get; set; }
        public string S237 { get; set; }
        public string S238 { get; set; }
        public string S239 { get; set; }
        public string S240 { get; set; }
        public string S241 { get; set; }
        public string S242 { get; set; }
        public string S243 { get; set; }
        public string S244 { get; set; }
        public string S245 { get; set; }
        public string S246 { get; set; }
        public string S247 { get; set; }
        public string S248 { get; set; }
        public string S249 { get; set; }
        public string S250 { get; set; }
        public string S251 { get; set; }
        public string S252 { get; set; }
        public string S253 { get; set; }
        public string S254 { get; set; }
        public string S255 { get; set; }
        public string S256 { get; set; }
        public string S257 { get; set; }
        public string S258 { get; set; }
        public string S259 { get; set; }
        public string S260 { get; set; }
        public string S261 { get; set; }
        public string S262 { get; set; }
        public string S263 { get; set; }
        public string S264 { get; set; }
        public string S265 { get; set; }
        public string S266 { get; set; }
        public string S267 { get; set; }
        public string S268 { get; set; }
        public string S269 { get; set; }
        public string S270 { get; set; }
        public string S271 { get; set; }
        public string S272 { get; set; }
        public string S273 { get; set; }
        public string S274 { get; set; }
        public string S275 { get; set; }
        public string S276 { get; set; }
        public string S277 { get; set; }
        public string S278 { get; set; }
        public string S279 { get; set; }
        public string S280 { get; set; }
        public string S281 { get; set; }
        public string S282 { get; set; }
        public string S283 { get; set; }
        public string S284 { get; set; }
        public string S285 { get; set; }
        public string S286 { get; set; }
        public string S287 { get; set; }
        public string S288 { get; set; }
        public string S289 { get; set; }
        public string S290 { get; set; }
        public string S291 { get; set; }
        public string S292 { get; set; }
        public string S293 { get; set; }
        public string S294 { get; set; }
        public string S295 { get; set; }
        public string S296 { get; set; }
        public string S297 { get; set; }
        public string S298 { get; set; }
        public string S299 { get; set; }
        public string S300 { get; set; }
        public string S301 { get; set; }
        public string S302 { get; set; }
        public string S303 { get; set; }
        public string S304 { get; set; }
        public string S305 { get; set; }
        public string S306 { get; set; }
        public string S307 { get; set; }
        public string S308 { get; set; }
        public string S309 { get; set; }
        public string S310 { get; set; }
        public string S311 { get; set; }
        public string S312 { get; set; }
        public string S313 { get; set; }
        public string S314 { get; set; }
        public string S315 { get; set; }
        public string S316 { get; set; }
        public string S317 { get; set; }
        public string S318 { get; set; }
        public string S319 { get; set; }
        public string S320 { get; set; }
        public string S321 { get; set; }
        public string S322 { get; set; }
        public string S323 { get; set; }
        public string S324 { get; set; }
        public string S325 { get; set; }
        public string S326 { get; set; }
        public string S327 { get; set; }
        public string S328 { get; set; }
        public string S329 { get; set; }
        public string S330 { get; set; }
        public string S331 { get; set; }
        public string S332 { get; set; }
        public string S333 { get; set; }
        public string S334 { get; set; }
        public string S335 { get; set; }
        public string S336 { get; set; }
        public string S337 { get; set; }
        public string S338 { get; set; }
        public string S339 { get; set; }
        public string S340 { get; set; }
        public string S341 { get; set; }
        public string S342 { get; set; }
        public string S343 { get; set; }
        public string S344 { get; set; }
        public string S345 { get; set; }
        public string S346 { get; set; }
        public string S347 { get; set; }
        public string S348 { get; set; }
        public string S349 { get; set; }
        public string S350 { get; set; }
        public string S351 { get; set; }
        public string S352 { get; set; }
        public string S353 { get; set; }
        public string S354 { get; set; }
        public string S355 { get; set; }
        public string S356 { get; set; }
        public string S357 { get; set; }
        public string S358 { get; set; }
        public string S359 { get; set; }
        public string S360 { get; set; }
        public string S361 { get; set; }
        public string S362 { get; set; }
        public string S363 { get; set; }
        public string S364 { get; set; }
        public string S365 { get; set; }
        public string S366 { get; set; }
        public string S367 { get; set; }
        public string S368 { get; set; }
        public string S369 { get; set; }
        public string S370 { get; set; }
        public string S371 { get; set; }
        public string S372 { get; set; }
        public string S373 { get; set; }
        public string S374 { get; set; }
        public string S375 { get; set; }
        public string S376 { get; set; }
        public string S377 { get; set; }
        public string S378 { get; set; }
        public string S379 { get; set; }
        public string S380 { get; set; }
        public string S381 { get; set; }
        public string S382 { get; set; }
        public string S383 { get; set; }
        public string S384 { get; set; }
        public string S385 { get; set; }
        public string S386 { get; set; }
        public string S387 { get; set; }
        public string S388 { get; set; }
        public string S389 { get; set; }
        public string S390 { get; set; }
        public string S391 { get; set; }
        public string S392 { get; set; }
        public string S393 { get; set; }
        public string S394 { get; set; }
        public string S395 { get; set; }
        public string S396 { get; set; }
        public string S397 { get; set; }
        public string S398 { get; set; }
        public string S399 { get; set; }
        public string S400 { get; set; }
        public string S401 { get; set; }
        public string S402 { get; set; }
        public string S403 { get; set; }
        public string S404 { get; set; }
        public string S405 { get; set; }
        public string S406 { get; set; }
        public string S407 { get; set; }
        public string S408 { get; set; }
        public string S409 { get; set; }
        public string S410 { get; set; }
        public string S411 { get; set; }
        public string S412 { get; set; }
        public string S413 { get; set; }
        public string S414 { get; set; }
        public string S415 { get; set; }
        public string S416 { get; set; }
        public string S417 { get; set; }
        public string S418 { get; set; }
        public string S419 { get; set; }
        public string S420 { get; set; }
        public string S421 { get; set; }
        public string S422 { get; set; }
        public string S423 { get; set; }
        public string S424 { get; set; }
        public string S425 { get; set; }
        public string S426 { get; set; }
        public string S427 { get; set; }
        public string S428 { get; set; }
        public string S429 { get; set; }
        public string S430 { get; set; }
        public string S431 { get; set; }
        public string S432 { get; set; }
        public string S433 { get; set; }
        public string S434 { get; set; }
        public string S435 { get; set; }
        public string S436 { get; set; }
        public string S437 { get; set; }
        public string S438 { get; set; }
        public string S439 { get; set; }
        public string S440 { get; set; }
        public string S441 { get; set; }
        public string S442 { get; set; }
        public string S443 { get; set; }
        public string S444 { get; set; }
        public string S445 { get; set; }
        public string S446 { get; set; }
        public string S447 { get; set; }
        public string S448 { get; set; }
        public string S449 { get; set; }
        public string S450 { get; set; }
        public string S451 { get; set; }
        public string S452 { get; set; }
        public string S453 { get; set; }
        public string S454 { get; set; }
        public string S455 { get; set; }
        public string S456 { get; set; }
        public string S457 { get; set; }
        public string S458 { get; set; }
        public string S459 { get; set; }
        public string S460 { get; set; }
        public string S461 { get; set; }
        public string S462 { get; set; }
        public string S463 { get; set; }
        public string S464 { get; set; }
        public string S465 { get; set; }
        public string S466 { get; set; }
        public string S467 { get; set; }
        public string S468 { get; set; }
        public string S469 { get; set; }
        public string S470 { get; set; }
        public string S471 { get; set; }
        public string S472 { get; set; }
        public string S473 { get; set; }
        public string S474 { get; set; }
        public string S475 { get; set; }


    }
}
